language: python

os:
  - linux

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install cython setuptools --upgrade

install:
  - python setup.py develop

script:
  - nosetests --with-doctest triangle/triangle.py

notifications:
  email: false
